export type BorderSide = "top" | "right" | "bottom" | "left";

// Playable board shape inferred from the initial board layout:
// rows 0-2 and 11-13 form the top/bottom bands, and rows 3-10 span the full width.
export const BOARD_PERIMETER_BORDER_MAP: Record<string, readonly BorderSide[]> =
  {
    "0,3": ["top", "left"],
    "0,4": ["top"],
    "0,5": ["top"],
    "0,6": ["top"],
    "0,7": ["top"],
    "0,8": ["top"],
    "0,9": ["top"],
    "0,10": ["top", "right"],
    "1,3": ["left"],
    "1,10": ["right"],
    "2,3": ["left"],
    "2,10": ["right"],
    "3,0": ["top", "left"],
    "3,1": ["top"],
    "3,2": ["top"],
    "3,11": ["top"],
    "3,12": ["top"],
    "3,13": ["top", "right"],
    "4,0": ["left"],
    "4,13": ["right"],
    "5,0": ["left"],
    "5,13": ["right"],
    "6,0": ["left"],
    "6,13": ["right"],
    "7,0": ["left"],
    "7,13": ["right"],
    "8,0": ["left"],
    "8,13": ["right"],
    "9,0": ["left"],
    "9,13": ["right"],
    "10,0": ["left", "bottom"],
    "10,1": ["bottom"],
    "10,2": ["bottom"],
    "10,11": ["bottom"],
    "10,12": ["bottom"],
    "10,13": ["right", "bottom"],
    "11,3": ["left"],
    "11,10": ["right"],
    "12,3": ["left"],
    "12,10": ["right"],
    "13,3": ["bottom", "left"],
    "13,4": ["bottom"],
    "13,5": ["bottom"],
    "13,6": ["bottom"],
    "13,7": ["bottom"],
    "13,8": ["bottom"],
    "13,9": ["bottom"],
    "13,10": ["bottom", "right"],
  };

export const getPerimeterBorderSides = (
  row: number,
  col: number,
): readonly BorderSide[] => BOARD_PERIMETER_BORDER_MAP[`${row},${col}`] ?? [];
